---
- name: "remote install git java-jdk11 jenkins" 
  hosts: slave
  tasks:
    - name : install git,python3,openssh-server packages>>>>>>
      ansible.builtin.yum:
        name: "{{ item }}"
        state: "latest"
      loop:
          - git
          - python3
          - openssh-server
    - name: installing java-jdk11>>> and jenkins>>>>>>
      ansible.builtin.command:
        cmd: "{{ item }}"
      loop: 
            - "wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo"
            - "rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key"
            - "yum upgrade"
            - "yum install java-11-openjdk"
            - "yum install jenkins"
            - "systemctl daemon-reload"
            - "systemctl start jenkins"
            - "firewall-cmd --add-port:8080/tcp --add-port:80/tcp --permanent"
            - "firewall-cmd --reload"
    - name: installing >>>docker>>>>>
      ansible.builtin.command:
        cmd: "{{ item }}"
      loop:
           - "yum install -y yum-utils"
           - "yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo" 
           - "yum install docker-ce docker-ce-cli containerd.io"

    - name: starting docker service
      ansible.builtin.service:
        name: docker.service
        state: "started "
        enabled: true
    
    